name: Deploy Angular to S3 + CloudFront

# Trigger the workflow on push to main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20' # adjust to your Angular Node version

      # 3️⃣ Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 4️⃣ Build Angular app
      - name: Build Angular
        run: npm run build -- --configuration production

      # 5️⃣ Deploy to S3
      - name: Deploy to S3
        uses: aws-actions/s3-sync@v2
        with:
          source_dir: 'dist'   # replace <project-name> with your Angular project folder
          dest_dir: '/'
          bucket: ${{ secrets.S3_BUCKET }}
          region: ${{ secrets.AWS_REGION }}
          delete: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 6️⃣ Invalidate CloudFront cache
      - name: Invalidate CloudFront Cache
        uses: aws-actions/cloudfront-invalidate@v2
        with:
          distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          paths: '/*'
          region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
